DROP TABLE IF EXISTS categorys;
CREATE TABLE categorys(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO categorys(name) VALUES('LAZER');
INSERT INTO categorys(name) VALUES('ALIMENTAÇÃO');
INSERT INTO categorys(name) VALUES('MERCADO');
INSERT INTO categorys(name) VALUES('COMBUSTÍVEL');
INSERT INTO categorys(name) VALUES('FARMÁCIA');
INSERT INTO categorys(name) VALUES('OUTROS');