INSERT INTO persons (address_sur_name, address_type, address_public_place, address_number, address_complement, address_neighborhood, address_cep, address_city, address_state, address_country, first_name, last_name, email, password, phone, bio, photo_url, job_title, job_description, active, created_at)
VALUES ('Santos', 'Residential', '123 Main Street', '1A', 'Apartment 5', 'Downtown', '12345-678', 'City', 'ST', 'Country', 'John', 'Doe', 'john.doe@example.com', 'password123', '555-1234', 'I am a software developer.', 'https://example.com/johndoe.jpg', 'Software Developer', 'Developing awesome applications', TRUE, '2022-01-01 10:00:00');

INSERT INTO persons (address_sur_name, address_type, address_public_place, address_number, address_complement, address_neighborhood, address_cep, address_city, address_state, address_country, first_name, last_name, email, password, phone, bio, photo_url, job_title, job_description, active, created_at)
VALUES ('Silva', 'Commercial', '456 Business Avenue', '10B', 'Floor 7', 'Business District', '98765-432', 'City', 'ST', 'Country', 'Maria', 'Silva', 'maria.silva@example.com', 'password456', '555-5678', 'I work in finance.', 'https://example.com/mariasilva.jpg', 'Finance Manager', 'Managing financial operations', TRUE, '2022-02-01 14:30:00');

INSERT INTO persons (address_sur_name, address_type, address_public_place, address_number, address_complement, address_neighborhood, address_cep, address_city, address_state, address_country, first_name, last_name, email, password, phone, bio, photo_url, job_title, job_description, active, created_at)
VALUES ('Oliveira', 'Residential', '789 Park Avenue', '20C', NULL, 'Suburb', '54321-876', 'City', 'ST', 'Country', 'Ana', 'Oliveira', 'ana.oliveira@example.com', 'password789', '555-9012', NULL, NULL, 'Marketing Specialist', 'Creating marketing campaigns', TRUE, '2022-03-15 09:45:00');

INSERT INTO persons (address_sur_name, address_type, address_public_place, address_number, address_complement, address_neighborhood, address_cep, address_city, address_state, address_country, first_name, last_name, email, password, phone, bio, photo_url, job_title, job_description, active, created_at)
VALUES ('Almeida', 'Residential', '987 Elm Street', '15D', NULL, 'Suburb', '87654-321', 'City', 'ST', 'Country', 'Pedro', 'Almeida', 'pedro.almeida@example.com', 'password123456', '555-3456', 'I love photography.', 'https://example.com/pedroalmeida.jpg', 'Photographer', 'Capturing beautiful moments', TRUE, '2022-04-20 16:20:00');

INSERT INTO persons (address_sur_name, address_type, address_public_place, address_number, address_complement, address_neighborhood, address_cep, address_city, address_state, address_country, first_name, last_name, email, password, phone, bio, photo_url, job_title, job_description, active, created_at)
VALUES ('Rocha', 'Commercial', '321 Business Avenue', '5C', 'Floor 2', 'Business District', '76543-210', 'City', 'ST', 'Country', 'Gabriel', 'Rocha', 'gabriel.rocha@example.com', 'password654321', '555-6789', 'I am a sales manager.', 'https://example.com/gabrielrocha.jpg', 'Sales Manager', 'Leading a sales team', TRUE, '2022-05-10 11:30:00');

INSERT INTO persons (address_sur_name, address_type, address_public_place, address_number, address_complement, address_neighborhood, address_cep, address_city, address_state, address_country, first_name, last_name, email, password, phone, bio, photo_url, job_title, job_description, active, created_at)
VALUES ('Ferreira', 'Residential', '654 Oak Street', '25A', NULL, 'Suburb', '23456-789', 'City', 'ST', 'Country', 'Camila', 'Ferreira', 'camila.ferreira@example.com', 'password987654', '555-8901', 'I enjoy cooking.', 'https://example.com/camilaferreira.jpg', 'Chef', 'Creating delicious dishes', TRUE, '2022-06-30 13:15:00');

INSERT INTO persons (address_sur_name, address_type, address_public_place, address_number, address_complement, address_neighborhood, address_cep, address_city, address_state, address_country, first_name, last_name, email, password, phone, bio, photo_url, job_title, job_description, active, created_at)
VALUES ('Santana', 'Commercial', '852 Business Avenue', '8D', 'Floor 5', 'Business District', '98765-432', 'City', 'ST', 'Country', 'Ricardo', 'Santana', 'ricardo.santana@example.com', 'password246813', '555-2345', 'I am a project manager.', 'https://example.com/ricardosantana.jpg', 'Project Manager', 'Managing software development projects', TRUE, '2022-07-25 09:00:00');

INSERT INTO persons (address_sur_name, address_type, address_public_place, address_number, address_complement, address_neighborhood, address_cep, address_city, address_state, address_country, first_name, last_name, email, password, phone, bio, photo_url, job_title, job_description, active, created_at)
VALUES ('Martins', 'Residential', '456 Maple Street', '12B', NULL, 'Suburb', '67890-123', 'City', 'ST', 'Country', 'Larissa', 'Martins', 'larissa.martins@example.com', 'password13579', '555-4567', 'I love playing sports.', 'https://example.com/larissamartins.jpg', 'Athlete', 'Training for competitions', TRUE, '2022-08-18 15:45:00');

INSERT INTO persons (address_sur_name, address_type, address_public_place, address_number, address_complement, address_neighborhood, address_cep, address_city, address_state, address_country, first_name, last_name, email, password, phone, bio, photo_url, job_title, job_description, active, created_at)
VALUES ('Gomes', 'Commercial', '123 Business Avenue', '3C', 'Floor 1', 'Business District', '76543-210', 'City', 'ST', 'Country', 'Renato', 'Gomes', 'renato.gomes@example.com', 'password97531', '555-6789', 'I am a marketing manager.', 'https://example.com/renatogomes.jpg', 'Marketing Manager', 'Developing marketing strategies', TRUE, '2022-09-12 12:30:00');

INSERT INTO persons (address_sur_name, address_type, address_public_place, address_number, address_complement, address_neighborhood, address_cep, address_city, address_state, address_country, first_name, last_name, email, password, phone, bio, photo_url, job_title, job_description, active, created_at)
VALUES ('Rodrigues', 'Residential', '987 Pine Street', '18D', NULL, 'Suburb', '23456-789', 'City', 'ST', 'Country', 'Laura', 'Rodrigues', 'laura.rodrigues@example.com', 'password75319', '555-8901', NULL, NULL, 'Teacher', 'Teaching students', TRUE, '2022-10-27 14:15:00');